import React from 'react';
import { FiCheck, FiX, FiCpu } from 'react-icons/fi';
import CodeDiff from './CodeDiff';

const FixSuggestion = () => {
    return (
        <div className="bg-surface-light rounded-xl border border-border-light shadow-sm p-6 mb-4">
            <div className="flex justify-between items-start mb-4">
                <div className="flex items-center">
                    <div className="p-2 bg-primary/10 rounded-lg text-primary mr-3">
                        <FiCpu className="text-xl" />
                    </div>
                    <div>
                        <h3 className="font-bold text-gray-900">SQL Injection Patch</h3>
                        <p className="text-sm text-muted-light">Generated by SafeOps AI • Confidence: 98%</p>
                    </div>
                </div>
                <div className="flex space-x-2">
                    <button className="px-3 py-1.5 text-sm font-medium text-muted-dark hover:bg-background-light rounded-lg transition-colors border border-transparent hover:border-border-light">
                        Dismiss
                    </button>
                    <button className="px-3 py-1.5 text-sm font-medium text-white bg-primary hover:bg-primary/90 rounded-lg shadow-sm transition-colors flex items-center">
                        <FiCheck className="mr-1.5" /> Apply Patch
                    </button>
                </div>
            </div>

            <p className="text-gray-600 text-sm mb-4">
                This fix replaces simple string concatenation with a prepared statement to prevent SQL injection attacks.
            </p>

            <CodeDiff />
        </div>
    );
};

export default FixSuggestion;
